stages:

- stage: BuildServices

  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: BuildDocker_SalesBookLB
    displayName: Build Docker Image For SalesBookLB app
  
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ContRegMultiStagePPLSvcConnection'
        repository: 'SalesBookLB'
        command: 'buildAndPush'
        Dockerfile: '**/SalesBook.LB/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'ContRegMultiStagePPLSvcConnection'
        repository: 'SalesBookWEB'
        command: 'buildAndPush'
        Dockerfile: '**/SalesBook.WEB/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest